### ISSUE TITLE
Null exception

### ISSUE THREAD

**Issue by dudeawsomeness1** [gottsch/gottsch-minecraft-MobDiceAttributes#2]
I made a 1.19.2 modpack with this mod in it, and it crashed with the message:

> Mob Dice Attributes (mobdiceattribs) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null

I tried running the game with only this mod (version 1.0.1), a fresh instance of minecraft 1.19.2, and Forge 43.2.8. I got the same error. Here is the full crash report from the isolated instance.
_I love the idea of this mod BTW 🙂_

[crash-2023-03-26_01.40.47-fml.txt](https://github.com/gottsch/gottsch-minecraft-MobDiceAttributes/files/11071029/crash-2023-03-26_01.40.47-fml.txt)

> ---- Minecraft Crash Report ----
> // You should try our sister game, Minceraft!
> 
> Time: 2023-03-26 01:40:47
> Description: Mod loading error has occurred
> 
> java.lang.Exception: Mod Loading has failed
> 	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19.2-43.2.8-universal.jar%23153!/:?] {re:classloading}
> 	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:167) ~[forge-1.19.2-43.2.8-universal.jar%23153!/:?] {re:classloading,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:585) ~[client-1.19.2-20220805.130853-srg.jar%23148!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.Util.m_137521_(Util.java:438) ~[client-1.19.2-20220805.130853-srg.jar%23148!/:?] {re:classloading}
> 	at net.minecraft.client.Minecraft.lambda$new$3(Minecraft.java:579) ~[client-1.19.2-20220805.130853-srg.jar%23148!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.19.2-20220805.130853-srg.jar%23148!/:?] {re:classloading,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:885) ~[client-1.19.2-20220805.130853-srg.jar%23148!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23148!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23148!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23148!/:?] {re:classloading,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23148!/:?] {re:classloading,pl:runtimedistcleaner:A}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
> 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
> 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.8.jar%23145!/:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%23132!/:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%23132!/:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%23132!/:?] {}
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%23132!/:?] {}
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%23132!/:?] {}
> 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%23132!/:?] {}
> 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%23132!/:?] {}
> 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
> 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
> 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc2.jar:mmc2] {}
> 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?] {}
> 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?] {}
> 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?] {}
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Render thread
> Stacktrace:
> 	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
> -- MOD mobdiceattribs --
> Details:
> 	Caused by 0: java.lang.reflect.InvocationTargetException
> 		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
> 		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
> 		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
> 		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
> 		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
> 		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.8.jar%23150!/:?] {}
> 		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.8.jar%23149!/:?] {}
> 		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
> 		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
> 		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
> 		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
> 		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
> 		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
> 		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
> 
> 	Caused by 1: java.lang.NoClassDefFoundError: mod/gottsch/forge/gottschcore/config/AbstractConfig
> 		at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] {}
> 		at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?] {}
> 		at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:119) ~[securejarhandler-2.1.4.jar:?] {}
> 		at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
> 		at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?] {}
> 		at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
> 		at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?] {}
> 		at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
> 		at mod.gottsch.forge.mda.MDA.<init>(MDA.java:53) ~[MobDiceAttributes-mc1.19.2-f43.2.0-v1.0.1.jar%23147!/:mc1.19.2-f43.2.0-v1.0.1] {re:classloading}
> 		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
> 		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
> 		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
> 		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
> 		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
> 		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.8.jar%23150!/:?] {}
> 		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.8.jar%23149!/:?] {}
> 		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
> 		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
> 		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
> 		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
> 		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
> 		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
> 		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
> 
> 	Mod File: /C:/Users/Invilis Bella/AppData/Roaming/PrismLauncher/instances/1.19.2(1)/.minecraft/mods/MobDiceAttributes-mc1.19.2-f43.2.0-v1.0.1.jar
> 	Failure message: Mob Dice Attributes (mobdiceattribs) has failed to load correctly
> 		java.lang.reflect.InvocationTargetException: null
> 	Mod Version: 1.0.1
> 	Mod Issue URL: https://github.com/gottsch/gottsch-minecraft-MobDiceAttributes/issues
> 	Exception message: java.lang.ClassNotFoundException: mod.gottsch.forge.gottschcore.config.AbstractConfig
> Stacktrace:
> 	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?] {}
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?] {}
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
> 	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] {}
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:119) ~[securejarhandler-2.1.4.jar:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
> 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?] {}
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
> 	at mod.gottsch.forge.mda.MDA.<init>(MDA.java:53) ~[MobDiceAttributes-mc1.19.2-f43.2.0-v1.0.1.jar%23147!/:mc1.19.2-f43.2.0-v1.0.1] {re:classloading}
> 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
> 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
> 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
> 	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
> 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.8.jar%23150!/:?] {}
> 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.8.jar%23149!/:?] {}
> 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
> 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
> 
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.19.2
> 	Minecraft Version ID: 1.19.2
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 17.0.3, Eclipse Adoptium
> 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
> 	Memory: 256494592 bytes (244 MiB) / 536870912 bytes (512 MiB) up to 4294967296 bytes (4096 MiB)
> 	CPUs: 4
> 	Processor Vendor: GenuineIntel
> 	Processor Name: Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
> 	Identifier: Intel64 Family 6 Model 94 Stepping 3
> 	Microarchitecture: Skylake (Client)
> 	Frequency (GHz): 3.50
> 	Number of physical packages: 1
> 	Number of physical CPUs: 4
> 	Number of logical CPUs: 4
> 	Graphics card #0 name: NVIDIA GeForce GTX 1060 6GB
> 	Graphics card #0 vendor: NVIDIA (0x10de)
> 	Graphics card #0 VRAM (MB): 4095.00
> 	Graphics card #0 deviceId: 0x1c03
> 	Graphics card #0 versionInfo: DriverVersion=31.0.15.3141
> 	Memory slot #0 capacity (MB): 8192.00
> 	Memory slot #0 clockSpeed (GHz): 2.13
> 	Memory slot #0 type: DDR4
> 	Memory slot #1 capacity (MB): 8192.00
> 	Memory slot #1 clockSpeed (GHz): 2.13
> 	Memory slot #1 type: DDR4
> 	Virtual memory max (MB): 26563.02
> 	Virtual memory used (MB): 14135.43
> 	Swap memory total (MB): 10240.00
> 	Swap memory used (MB): 321.46
> 	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
> 	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
> 	ModLauncher launch target: forgeclient
> 	ModLauncher naming: srg
> 	ModLauncher services: 
> 		mixin-0.8.5.jar mixin PLUGINSERVICE 
> 		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
> 		fmlloader-1.19.2-43.2.8.jar slf4jfixer PLUGINSERVICE 
> 		fmlloader-1.19.2-43.2.8.jar object_holder_definalize PLUGINSERVICE 
> 		fmlloader-1.19.2-43.2.8.jar runtime_enum_extender PLUGINSERVICE 
> 		fmlloader-1.19.2-43.2.8.jar capability_token_subclass PLUGINSERVICE 
> 		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
> 		fmlloader-1.19.2-43.2.8.jar runtimedistcleaner PLUGINSERVICE 
> 		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
> 		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
> 	FML Language Providers: 
> 		minecraft@1.0
> 		lowcodefml@null
> 		javafml@null
> 	Mod List: 
> 		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
> 		forge-1.19.2-43.2.8-universal.jar                 |Forge                         |forge                         |43.2.8              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
> 		MobDiceAttributes-mc1.19.2-f43.2.0-v1.0.1.jar     |Mob Dice Attributes           |mobdiceattribs                |1.0.1               |ERROR     |Manifest: NOSIGNATURE
> 	Crash Report UUID: e4e0e764-4dbb-4274-8034-e068d17f983f
> 	FML: 43.2
> 	Forge: net.minecraftforge:43.2.8

**Comment by dudeawsomeness1** [comment]
I see now, it requires "gottschcore" (https://modrinth.com/mod/gottschcore). Usually, Minecraft will tell you what library/core/API mods are missing, so I don't know if that's something you have to program it to do?
Either way you might want to explicitly state the requirement on the mod pages.
